version: '3'
services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8671:8671"
  user-service:
    build: ./user-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
  template-service:
    build: ./template-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
  notification-service:
    build: ./notification-service
    ports:
      - "8081:8081"
    depends_on:
      - user-service
      - template-service
      - discovery-service