CREATE TABLE USERS
(
  ID         INT         NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(40) NOT NULL,
  SURNAME    VARCHAR(60) NOT NULL,
  GENDER     VARCHAR(40) NOT NULL,
  EMAIL      VARCHAR(40) NOT NULL,
  SUBSCRIBED BOOLEAN,
--   UNIQUE UQ_USER_1 (EMAIL),
  PRIMARY KEY (ID)
);
